auto generate docs and deploy to github pages
jcam1/sdks pull request #86
Opened 2024-12-05 10:43 UTC by Mameta29

# 🎨 Overview
Implement auto-generation of documentation and modified the documentation generation to output both HTML (for GitHub Pages) and Markdown (for GitHub) formats.

# 🌈 Details
- Implement workflow file `deploy-docs.yml` for git action to deploy docs to github pages
- Configure to generate Markdown documentation under `/docs/core` - for GitHub repository viewing
- Configure to generate HTML documentation under `/docs/core-html` - for GitHub Pages hosting
- Update TypeDoc configurations:
 - Remove `plugin` setting from root `typedoc.json`, keeping only essential configs
 - Add `docs:md` and `docs:html` scripts to `packages/core`
 - Set HTML documentation output directory to `core-html`
- Add `docs/core-html` to `.prettierignore` to exclude from formatting checks

# 📚 References
- Issue #59: Enable Auto-Deployments of Docs/Specs
- Previous related PRs: #74, #75, #76, #77, #78, #81

This change enables proper generation and management of both Markdown documentation for GitHub viewing and HTML documentation for GitHub Pages.

2024-12-05 12:07 UTC, SeiyaKobayashi requested changes
何点かコメントしました！

2024-12-05 12:07 UTC, SeiyaKobayashi commented on .github/workflows/deploy-docs.yml
> +          yarn workspace @jpyc/sdk-core run format
`build` という命名のジョブに含まれていますが、これは単純なフォーマットチェックなので違うジョブとして定義し、`needs` キーワードでジョブの実行条件を制限してあげる方が良さそうです

2024-12-05 12:07 UTC, SeiyaKobayashi commented on .github/workflows/deploy-docs.yml
> +          yarn workspace @jpyc/sdk-core run format
実際にここでフォーマッティングする必要はないので、`format:dry-run` で良いかと思います (フォーマットエラーであればどちらにせよ `check.yml` で落とされます)

2024-12-05 12:07 UTC, SeiyaKobayashi commented on .github/workflows/deploy-docs.yml
> +      url: ${{ steps.deployment.outputs.page_url }}
実際にデプロイされるとどういった感じになるのか URL をいただきたいです

2024-12-06 00:19 UTC, Mameta29 commented on packages/core/package.json
> +    "docs:md": "typedoc --plugin typedoc-plugin-markdown --out ../../docs/core",
コマンドラインを修正しました。

2024-12-06 00:19 UTC, Mameta29 commented on packages/core/package.json
> +    "docs:html": "typedoc --out ../../docs/core-html"
コマンドラインを修正しました。

2024-12-06 00:25 UTC, Mameta29 commented on packages/core/package.json
> +    "docs": "yarn docs:md && yarn docs:html",
並列処理できるのいいですね。ご提案ありがとうございます。

2024-12-06 00:25 UTC, Mameta29 commented on .github/workflows/deploy-docs.yml
> +    branches: ['develop']
mainがトリガーになること良いと思います。修正します。

2024-12-06 00:25 UTC, Mameta29 commented on .github/workflows/deploy-docs.yml
> +        run: yarn install --frozen-lockfile
見落としておりました。そちら使用します。

2024-12-06 00:31 UTC, Mameta29 commented on .github/workflows/deploy-docs.yml
> +      - 'packages/*/src/**'
docs/**'
こちら削除します。

2024-12-06 01:24 UTC, Mameta29 commented on .github/workflows/deploy-docs.yml
> +          yarn workspace @jpyc/sdk-core run format
format は別でわけ、format:dry-runで統一しました。

2024-12-06 03:22 UTC, SeiyaKobayashi commented on .github/workflows/deploy-docs.yml
> +      - 'packages/*/src/**'
`packages/*/src/**` を削除いただきたいです！

2024-12-06 03:22 UTC, SeiyaKobayashi commented on .github/workflows/deploy-docs.yml
> +        run: yarn install --frozen-lockfile
お願いします！

2024-12-06 03:27 UTC, SeiyaKobayashi requested changes
追加でコメントしました

2024-12-06 09:20 UTC, Mameta29 commented on .github/workflows/deploy-docs.yml
> +        run: yarn install --frozen-lockfile
[97d8a4b](https://github.com/jcam1/sdks/pull/86/commits/97d8a4bf61eadad377163db221fe42165203309f)

2024-12-06 09:24 UTC, Mameta29 commented on .github/workflows/deploy-docs.yml
> +      - 'packages/*/src/**'
修正しました
[8f5b89c](https://github.com/jcam1/sdks/pull/86/commits/8f5b89ce77413bf15e1dc4df9787e04595fc632e)

2024-12-06 10:13 UTC, SeiyaKobayashi approved these changes
一点コメントしましたがそれが修正されれば LGTM です！

2024-12-06 10:13 UTC, SeiyaKobayashi commented on .github/workflows/deploy-docs.yml
> +          }
ドキュメントの生成はしなくて良いので、ここは不要です

2024-12-09 02:13 UTC, Mameta29 commented on .github/workflows/deploy-docs.yml
> +          }
追加でformat チェックから @jpyc/sdk-core の部分を削除しました。
[4d07caf](https://github.com/jcam1/sdks/pull/86/commits/4d07caf0da08940805a2576ecc98601911dbb5a6)

2024-12-10 06:39 UTC, merged